### ISSUE TITLE
consider if wheels are an option for pip packages

### ISSUE THREAD

**Issue by AndrewGearhart** [open-oni/open-oni#283]
PIP prefers wheels and it sounds like they are compiled in-advance where they're used.

May be an option since we're locking to pip package versions.

See https://packaging.python.org/tutorials/installing-packages/#source-distributions-vs-wheels

**Comment by techgique** [comment]
Maybe https://github.com/open-oni/open-oni/pull/359/commits/08b33a10ce4b1f663fcabfa84cddfb3411041d44 addresses this issue?

**Comment by techgique** [comment]
Following up on Python-related issues after #534 was just merged. We _could_ build wheels of the packages that aren't already distributed as such from PyPI, but the only difference is a modest amount of install time. I haven't seen any of the packages take long to install lately. I think in the past it was taking longer due to slower compilations of some of the packages happening. I think the commit I referenced above which relates to using a newer version of `pip` resolved those longer package installs.

If there are other considerations, let me know. Otherwise I'm guessing we can close this issue.
