### ISSUE TITLE
Can we throw away /titles?

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#310]
Does that URL give us anything that `/newspapers` isn't already giving us?  Is there any good reason to hold onto the excess code and templates?

**Comment by jduss4** [comment]
Yes, I believe it has filtering / searching.  If we end up using something like the ideas in #190, then we don't need it anymore.  As it is, we are probably currently not using it simply because we don't have enough titles to make it worth it, but I could definitely see wanting to filter down titles easily if somebody wanted to say, look at the list of newspapers in German or those that ran before 1820, etc.  Note, one of my examples isn't wonderful because there's a report for that already :P

**Comment by jechols** [comment]
Okay, let's close this then
