### ISSUE TITLE
Add Rights Metadata and Display

### ISSUE THREAD

**Issue by kestlund** [open-oni/open-oni#37]

**Comment by srabun** [comment]
Our current Oregon hack for displaying rights statements with content is presenting potential problems. Need to figure out a solution that could work for us and everyone. Ask @jechols and/or @lsat12357 for more info...

**Comment by jechols** [comment]
Current implementation:

- We tie a rights URL to an LCCN in a custom LCCN admin tool
- When an issue is generated, we look up the rights URL and stuff it into the issue XML
- The ingest ties the issue directly to a given rights URL in the database

Problems with this:

- An LCCN can, over a span of enough time, have multiple rights statements
- Baking rights into the issue XML means fixes involve a database change *and* a file change **per issue**
- Changing the XML file post-ingest invalidates the batch's bag checksums, which can lead to a lack of confidence in data integrity, and broken data if the original batch has to be reingested.

My suggestion is some kind of rules within ONI that allows for displaying rights for a page in a dynamic way.  If it turns out the rights statement was wrong, it's a relatively simple rules fix rather than a huge manual effort changing XML and possibly thousands of issues' rights statements.  Ideally these rules would be data-driven and based on a simple matrix (like LCCN + date range = copyright_id) so that rules administration is simple.

**Comment by srabun** [comment]
find way to associate rights with LCCN and dates/time ranges?
