### ISSUE TITLE
Pennsylvania State Library missing from core_awardee table

### ISSUE THREAD

**Issue by AndrewGearhart** [open-oni/open-oni#440]
Recognizing that we want to get rid of this table, in the meantime it is necessary as part of the loading process. It would be nice to get some of the other needed awardees into the datatables by default. For example:
```
org_code | name                                                                 | created
p        | Pennsylvania State Library, Harrisburg, PA                           | 1975-07-25 00:00:00
```

**Comment by techgique** [comment]
I believe https://github.com/open-oni/open-oni/blob/master/core/fixtures/awardees.json is the file you're looking for. Our friend on Slack, Tinghui Duan, updated the list with more awardees from LoC / NDNP. Should probably do that again at the same time.

Also be careful of https://github.com/open-oni/open-oni/commit/d0f8937ff2182b78d171bc7e6285838c9016eccd if we do update the whole list.

**Comment by jduss4** [comment]
I think we can get at the current chronicling america list through a variation on this url:  https://chroniclingamerica.loc.gov/awardees.json

@AndrewGearhart is the Penn State Library an official awardee in NDNP or is this a custom requirement?

**Comment by jechols** [comment]
If they're not an official awardee, they have to be managed locally, otherwise y'all are going to go nuts when UO starts putting our awardees in ONI: we have about 30 custom awardees for digitization work that wasn't done through NDNP funding.

Looking over the official list in Chronicling America, and the fact that "p" is the awardee's org code, I'm guessing this one is custom, and therefore needs to either apply to be an official NDNP grant awardee, or else they have to be managed locally for whomever needs them.

I suggest we simply continue to mirror the official list from chronam and keep our data up-to-date that way.

**Comment by jduss4** [comment]
It looks like we don't have any management commands for adding awardee information, which might be helpful in this case so that users don't have to override the open oni awardees json file.

**Comment by jechols** [comment]
Hmm, agreed.  Let’s create a ticket for that.  We have to modify awardees probably half a dozen times a year, and each time is an exercise in PAIN.

This is one of those things I really want to expose an API to do for us, but I think a management command is a much more realistic 1.0 (or 1.1) goal.

**Comment by jechols** [comment]
Oh lovely - email responses put a ton of crap into them.  I won't be doing *that* again.

**Comment by jechols** [comment]
Added a ticket: #453

**Comment by jechols** [comment]
Closing this - I think we all agree we don't want to add one-offs to the core fixtures, and some work is necessary (and ticketed) to get a command in
