### ISSUE TITLE
Hardware Requirements Documentation

### ISSUE THREAD

**Issue by techgique** [open-oni/open-oni#472]
We've discussed this in Slack, but we should add documentation into the repo itself.

**Comment by jechols** [comment]
UO is probably a good baseline - we get a ton of traffic for our server's power, especially when you look at the number of bots we let spider things.

- We have about 1.2 million unique newspaper pages.  About 1/2 are color.  Color pages use about 3x the RAM and CPU as monochrome.
- In any given week, we see roughly 35,000 user page requests, but roughly **ten times** that many bot page requests
  - To be clear, I'm not talking about *asset* requests.  I'm talking about HTML requests, and specifically for individual newspaper page views (since those are the easiest to find bot traffic against)

To power this, our server has 2 vCPUs and 5 gigs of RAM.  This server runs Apache (using the Django wsgi stuff), MySQL, Solr, RAIS as well as the batch ingests when those happen.  i.e., it's a monolith with no separation of services, because it's one of the very few projects that just has never needed separation.  Our Solr instance still runs on the default 512m of heap space.

Disk space is going to be impossible to guess at for people, because it depends so much on the quantity and quality of newspapers.  For JP2-only collections, it can be 1/10th the size of collections that have TIFFs.  If people scan at 150dpi (lower than the NDNP spec, but it does happen sometimes), that's an order of magnitude smaller than 600dpi scans (150x150 vs. 600x600).  Color images are 3x the size of monochrome.

Hopefully adopters will already know how much storage their setup is going to require.  If not, we may have to state that storage can vary drastically.  If coded to NDNP spec minimums, and monochrome, an okay ballpark is probably one terabyte per 25,000 pages.  (Our 1.2 million pages are a bit misleading since a lot of them have no TIFFs - born-digital issues are much easier to store)

Solr, MySQL, and word coordinates can use a fair amount of storage with big collections (~100 gigs for us), but it's a very small fraction of the storage needed just for the JP2s (about 3 or 4 TB for us).

**Comment by jechols** [comment]
Hmm, it's worth noting that these specs are for ONI 0.10.  I do not know if the 1.0 update will require more hardware (Solr's update in particular is a big unknown).

**Comment by techgique** [comment]
I'm trying to summarize this for the README. @jechols how does this look?

### Hardware Requirements

This is a ballpark estimate of what we recommend for running Open ONI in
production:

CPU | Memory | Storage
----|--------|--------
Modern CPU with two (virtual) cores | 4GB | Approximately 1TB per 25,000 pages

Based largely on University of Oregon's traffic, these resources can power
35,000 user page requests and roughly ten times that amount of bot page requests
in a week. So Open ONI is quite capable with minimal server processing and
memory resources.
