### ISSUE TITLE
Figure out how to fix IIIF presentation manifests

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#483]
I just discovered while working on #474 that the JSON manifests crash the app completely if there are pages that were published but not digitized.  I'm working around this temporarily by having the page return an empty JSON object, but I suspect that violates the IIIF presentation spec.  It's just a work-around to keep the app from having a hard crash, so it makes sense to get *something* rather than continuing to let things crash, but this needs attention.

The original API from chronam was a wholly different output, and for some reason very early in ONI's life we chose to replace it wholesale - which has caused a variety of problems for us at UO (see #302 for a bit about this).  Maybe it's time to really look closer at this and figure out the right solution.

My recommendation is to rip out all the models' `json` functions and implement any API endpoints either in a separate module (this isn't business logic and doesn't belong in the model anyway) or in a completely separate plugin, maintained by those who need whatever functionality is implemented.  This is, in fact, exactly what UO has done, albeit in our theme rather than in a separate plugin: https://github.com/uoregon-libraries/oregon-oni/blob/master/json_api.py

**Comment by techgique** [comment]
@jduss4 is probably the person to look at the IIIF presentation manifests and more familiar with the spec.

I've thought for a while that the `json` functions in the models seemed odd. I'm guessing it was just done that way for ease / speed's sake. I'm open to the idea of separating out the API endpoints as a separate module and making it friendlier to overriding / customizing via plugin.

There may be a reasonable fix for the IIIF manifests in the short term, but I'm imagining the API endpoints will be a separate much larger issue.

**Comment by AndrewGearhart** [comment]
@jechols I'm wondering where exactly this occurs. When I pull items from the PA News Archive that don't have OCR data... I'm able to still get the manifest JSON for the issue. The manifest doesn't correctly validate due to the height and width being identified as null (they are used for proportions, so they should be proportional values and need not be specific numbers other than for this purpose ex height 571, width 378 to indicate US Broadsheet in mm). However, I don't run into a crash. Am I looking at a different part of the system? I'm looking at an example issue manifest:

https://panewsarchive.psu.edu/lccn/sn86071314/1848-11-02/ed-1.json

**Comment by jechols** [comment]
Okay, I have a fix in the works.  It will prevent the crash, but it will not actually fix our bigger problem here.  Revisiting the IIIF API is still a must.

**Comment by AndrewGearhart** [comment]
As discussed in Slack. As we consider the API structure, we should probably outline with Open API spec (ie Swagger).

**Comment by raybrarian** [comment]
Does this need a new issue to clarify?

**Comment by jechols** [comment]
Nope, this should be closed. We already have a ticket for considering the IIIF API, and anything beyond that is way outta scope (for now at least)
