### ISSUE TITLE
Batch page does not correctly identify edition number in URL

### ISSUE THREAD

**Issue by AndrewGearhart** [open-oni/open-oni#494]
The batch page at `/batch/<batchname>/` does not correctly generate the link to the issue(s) if there is an edition that is not a first edition. 

For example, a second edition on a particular date would identify an editionOrder="2" and the xml file identified for the issue would customarily be named `YYYYMMDDEE` where EE is the edition. This should lead to the URL being generated on this page of 
`http://hostname/lccn/<TITLE-LCCN>/<YYYY>-<MM>-<DD>/ed-<E>/`
However, this page is generating ed-1 always.

The regular flow for identifying the edition number and including it as part of the link seems to work just fine in all other locations tested.

**Comment by AndrewGearhart** [comment]
Compare https://github.com/open-oni/open-oni/blob/8e2503ae9ca8c72b08f506789146866ef8b4dd2b/core/templates/issue_pages.html#L26
With the incorrect:
https://github.com/open-oni/open-oni/blob/8e2503ae9ca8c72b08f506789146866ef8b4dd2b/core/templates/reports/batch.html#L69

**Comment by techgique** [comment]
Good catch and tags! :+1:

**Comment by gabbyprecious** [comment]
Hello, can you explain more so I can work on it?

**Comment by jduss4** [comment]
Hi @gabbyprecious , sorry that nobody responded to your question sooner! It would appear that in the `batch.html` file, the final argument being passed into `openoni_issue_pages` is "1" for edition, but in some cases an issue ("issue" here refers to a single newspaper publication, like a Sunday morning paper on May 1, 1990, for example) might not be the first edition. @AndrewGearhart has discovered that we should instead be using `issue.edition` so that the correct number is passed in.

The fix for this issue is minimal, but the setup to get Open ONI may take a little bit of work. You will need to follow our docker installation instructions to get the software running and then add a newspaper batch so that you can test out the `batches/[batch name]` URL.

If you are still looking for something to work on, you are welcome to tackle this issue! Somebody from the open oni core maintainer team may address it soon as well, as we are working through some other bugs right now at the moment :)

**Comment by BusinessFawn** [comment]
Is this still an issue? I'm looking for something I can help out with.
