### ISSUE TITLE
Discuss CTS and Essays

### ISSUE THREAD

**Issue by jechols** [open-oni/open-oni#68]
Looking at the settings I noticed two sections where settings point to URLs that are no longer valid: CTS_xxx and ESSAYS_FEED.  If the URLs are dead, do we have any use for the settings and the underlying code?

We need to figure out if we want to fix and maintain the settings and code, or destroy it.  Ticket(s) should be created to take the appropriate action(s) after discussion(s).

**Comment by edsu** [comment]
The CTS_XXX configuration and related code can be completely removed. That was for communicating batch load/purge events with the repository inventory system at LC.

The essays are textual description of a particular newspaper that NDNP awardees create. For example the description on the right of the screen in the newspaper display for [Daily Globe](http://chroniclingamerica.loc.gov/lccn/sn83025287/). That content is not found in the NDNP batch data and is instead managed by an internal application at the Library of Congress called the Essay Editor. The Essay Editor makes the content of the essays available as an Atom feed. But since it isn't public openoni can't load them.

I don't know if these descriptions are important for openoni. In theory it should be possible to get a snapshot of the existing essays and make them part of openoni somehow.

**Comment by jechols** [comment]
Good to know, thanks!  Sounds like the essays might take some work, but the CTS stuff can just be dropped immediately.

**Comment by jechols** [comment]
@karindalziel: you guys use the essays, correct?  Do you have an app that loads them into the database?  I'm thinking if we want to support essays (and we probably do), we need some way for people to populate them.

Pushing this to milestone 2 since it seems pretty important, but not immediately pressing.

**Comment by jduss4** [comment]
@AndrewGearhart was just asking me about essay loading when I saw nobody had answered your question, @jechols .

Back in the day, when I didn't have immediate success using the essay loader (I am not sure how it works still...or if it works?), I just entered our 13 or so essays into the database by hand, including the join tables.  It is obviously not a great solution, but it was a one time solution for us.

I would really like a permanent solution for essay loading, especially because that would save Oregon from having to make dozens of individual pages to host their essays and then put in custom links for them, etc.  Title pages do display essays if they are joined correctly in the database, and that's functionality that we can use to our advantage.  We should figure out how the ideal essay loading situation would go down (GUI, config file, etc) at some point.

**Comment by jechols** [comment]
Hmm, I think this needs a new ticket?  I'd love a nice GUI editor so non-tech folks could set up their essays, but I think we'll want a command-line-only solution at least for initial release.

We could also try to figure out if an essay already exists by hitting the chronam site.  It would be a pretty raw screen-scrape, but it sure would save people a lot of time re-entering data LC already has.

**Comment by jduss4** [comment]
I think I will open a new ticket for this, because we have some brainstorming ideas for adding essays!
